//
//  MyGroupsModels.swift
//  VK client
//
//  Created by Денис Сизов on 06.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MyGroups
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
		
    }
    struct Response
    {
		
    }
    struct GroupModel
    {
		let name: String
		let image: String
		let id: Int
    }
  }
}
