//
//  MyGroupsInteractor.swift
//  VK client
//
//  Created by Денис Сизов on 06.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyGroupsBusinessLogic
{
  func doSomething(request: MyGroups.Something.Request)
}

protocol MyGroupsDataStore
{
  //var name: String { get set }
}

class MyGroupsInteractor: MyGroupsBusinessLogic, MyGroupsDataStore
{
  var presenter: MyGroupsPresentationLogic?
  var worker: MyGroupsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MyGroups.Something.Request)
  {
    worker = MyGroupsWorker()
    worker?.doSomeWork()
    
    let response = MyGroups.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
