//
//  MyGroupsPresenter.swift
//  VK client
//
//  Created by Денис Сизов on 06.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyGroupsPresentationLogic
{
  func presentSomething(response: MyGroups.Something.Response)
}

class MyGroupsPresenter: MyGroupsPresentationLogic
{
  weak var viewController: MyGroupsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MyGroups.Something.Response)
  {
    let viewModel = MyGroups.Something.GroupModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
